name: musiclearn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - scipy
  - numpy==1.19.5
  - tensorflow-gpu
  - matplotlib
  - scikit-learn
  - black
  - pylint
  - jupyter
  - python-dotenv
  - pytest
  - music21
  - pip
  - readline
  - pydot
  - click
  - seaborn
  - jupytext
  - pip:
    - midi2audio
